name: Linux

on:
  push:
    branches: [ master, '*-ci' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_linux:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv

    - name: Build Zserio PyPi
      run: scripts/build.sh

    - name: Test Zserio PyPi
      run: scripts/test.sh
      env:
        PYLINT_ENABLED: 1
        MYPY_ENABLED: 1

    - name: Archive Zserio PyPi binaries
      uses: actions/upload-artifact@v3
      with:
        name: zserio-pypi-${{matrix.os}}
        path: distr/*
